FROM golang:1.24 AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN go build -o main .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/main /app/main

# # Create non-root user
# USER 1000:1000

CMD ["/app/main"]